version: '3' # composeファイルのバーション指定
services:
  golang1.:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    tty: true # コンテナの起動永続化
    volumes:
      - .:/go/src/work # マウントディレクトリ指定
